### ISSUE TITLE
검색 기능 사용 시 검색어가 input 컴포넌트에 남아있음

### ISSUE THREAD

**Issue by sleepyeePanda** [RecruitDSM/frontend#2]
## 기대 결과
검색창에 기업명을 입력하고 검색 버튼을 클릭하면 검색 결과를 확인할 수 있고 검색창의 입력 내용은 지워져야 함.

## 현재 결과
검색창에 기업명을 입력하고 검색 버튼을 클릭하면 검색 결과는 확인할 수 있으나 검색창의 입력 내용이 지워지지 않고 남아 있음.

**Comment by soheejang15** [comment]
검색 창에 키워드 입력 후 검색 시 키워드 삭제되도록 수정.

## 추가 수정 사항
- 키워드 앞 뒤 공백 제외 검색
- 공백일 시 검색 불가
- Input 창 focus 상태에서 Enter 입력 시 검색
